---
title: Все об Arch Linux
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Arch Linux будет тем, что вы из него сделаете!
baseurl: ''
url: https://ordanax.github.io
permalink: "/:title"
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
paginate: 7
# Комментарии через Utterances (хранятся в GitHub Issues)
github_repo: ordanax/ordanax.github.io

exclude:
- Gemfile
- Gemfile.lock